"""add document ingest fingerprints

Revision ID: 40da70669f47
Revises: b5b3406cc506
Create Date: 2026-01-09 02:03:34.723858

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40da70669f47"
down_revision: Union[str, Sequence[str], None] = "b5b3406cc506"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("content_sha256", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "documents",
        sa.Column("ingest_fingerprint", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "documents", sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "ingested_at")
    op.drop_column("documents", "ingest_fingerprint")
    op.drop_column("documents", "content_sha256")
    # ### end Alembic commands ###
