"""fix tenant composite fks

Revision ID: b5b3406cc506
Revises: 379292e88fcf
Create Date: 2026-01-08 02:06:53.773843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5b3406cc506'
down_revision: Union[str, Sequence[str], None] = '379292e88fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) ENUM renames (do this first; it avoids noisy alter_column diffs)
    op.execute("ALTER TYPE aclsubjecttype RENAME TO acl_subject_type;")
    op.execute("ALTER TYPE documentstatus RENAME TO document_status;")

    # 2) Add unique constraint needed for composite FK target
    op.create_unique_constraint(
        "uq_documents_tenant_id_id",
        "documents",
        ["tenant_id", "id"],
    )

    # 3) CHUNKS: drop old FK(document_id)->documents(id), add composite FK
    # NOTE: replace the constraint name below with the actual one from your generated migration
    op.drop_constraint("chunks_document_id_fkey", "chunks", type_="foreignkey")
    op.create_foreign_key(
        "fk_chunks_tenant_document",
        "chunks",
        "documents",
        ["tenant_id", "document_id"],
        ["tenant_id", "id"],
        ondelete="CASCADE",
    )

    # 4) DOCUMENT_ACLS: drop old FK(document_id)->documents(id), add composite FK
    op.drop_constraint("document_acls_document_id_fkey", "document_acls", type_="foreignkey")
    op.create_foreign_key(
        "fk_docacls_tenant_document",
        "document_acls",
        "documents",
        ["tenant_id", "document_id"],
        ["tenant_id", "id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    # Reverse order

    op.drop_constraint("fk_docacls_tenant_document", "document_acls", type_="foreignkey")
    op.create_foreign_key(
        "document_acls_document_id_fkey",
        "document_acls",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_constraint("fk_chunks_tenant_document", "chunks", type_="foreignkey")
    op.create_foreign_key(
        "chunks_document_id_fkey",
        "chunks",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_constraint("uq_documents_tenant_id_id", "documents", type_="unique")

    op.execute("ALTER TYPE acl_subject_type RENAME TO aclsubjecttype;")
    op.execute("ALTER TYPE document_status RENAME TO documentstatus;")